import type { FastifyPluginAsync } from "fastify";
import { Type } from "@sinclair/typebox";

const ModelRouteSchema = Type.Object({
  id: Type.String(),
  label: Type.String(),
  family: Type.String(),
  mode: Type.Union([
    Type.Literal("fast"),
    Type.Literal("balanced"),
    Type.Literal("studio"),
  ]),
  capabilities: Type.Array(Type.String()),
  languages: Type.Array(Type.String()),
  approval: Type.Union([
    Type.Literal("approved"),
    Type.Literal("evaluation"),
    Type.Literal("license-blocked"),
  ]),
  releaseStage: Type.Union([
    Type.Literal("internal"),
    Type.Literal("beta"),
    Type.Literal("ga"),
  ]),
  localEligible: Type.Boolean(),
});

const modelRoutes = [
  {
    id: "kokoro-82m@evaluation",
    label: "Kokoro 82M",
    family: "kokoro",
    mode: "fast",
    capabilities: ["preset-tts"],
    languages: ["en"],
    approval: "evaluation",
    releaseStage: "internal",
    localEligible: true,
  },
  {
    id: "luxtts@evaluation",
    label: "LuxTTS",
    family: "luxtts",
    mode: "fast",
    capabilities: ["voice-clone"],
    languages: ["en"],
    approval: "evaluation",
    releaseStage: "internal",
    localEligible: true,
  },
  {
    id: "qwen3-tts-0.6b-base@evaluation",
    label: "Qwen3-TTS 0.6B Base",
    family: "qwen3-tts",
    mode: "balanced",
    capabilities: ["voice-clone", "multilingual"],
    languages: ["en", "zh", "ja", "ko", "de", "fr", "ru", "pt", "es", "it"],
    approval: "evaluation",
    releaseStage: "internal",
    localEligible: false,
  },
  {
    id: "qwen3-tts-1.7b-base@evaluation",
    label: "Qwen3-TTS 1.7B Base",
    family: "qwen3-tts",
    mode: "studio",
    capabilities: ["voice-clone", "multilingual"],
    languages: ["en", "zh", "ja", "ko", "de", "fr", "ru", "pt", "es", "it"],
    approval: "evaluation",
    releaseStage: "internal",
    localEligible: false,
  },
  {
    id: "qwen3-tts-0.6b-customvoice@evaluation",
    label: "Qwen3-TTS 0.6B CustomVoice",
    family: "qwen3-tts",
    mode: "balanced",
    capabilities: ["preset-tts", "instruction-control", "multilingual"],
    languages: ["en", "zh", "ja", "ko", "de", "fr", "ru", "pt", "es", "it"],
    approval: "evaluation",
    releaseStage: "internal",
    localEligible: false,
  },
  {
    id: "qwen3-tts-1.7b-customvoice@evaluation",
    label: "Qwen3-TTS 1.7B CustomVoice",
    family: "qwen3-tts",
    mode: "studio",
    capabilities: ["preset-tts", "instruction-control", "multilingual"],
    languages: ["en", "zh", "ja", "ko", "de", "fr", "ru", "pt", "es", "it"],
    approval: "evaluation",
    releaseStage: "internal",
    localEligible: false,
  },
  {
    id: "qwen3-tts-1.7b-voicedesign@evaluation",
    label: "Qwen3-TTS 1.7B VoiceDesign",
    family: "qwen3-tts",
    mode: "studio",
    capabilities: ["voice-design", "instruction-control", "multilingual"],
    languages: ["en", "zh", "ja", "ko", "de", "fr", "ru", "pt", "es", "it"],
    approval: "evaluation",
    releaseStage: "internal",
    localEligible: false,
  },
  {
    id: "chatterbox-multilingual@evaluation",
    label: "Chatterbox Multilingual",
    family: "chatterbox",
    mode: "balanced",
    capabilities: ["voice-clone", "multilingual"],
    languages: [],
    approval: "evaluation",
    releaseStage: "internal",
    localEligible: false,
  },
  {
    id: "chatterbox-turbo@evaluation",
    label: "Chatterbox Turbo",
    family: "chatterbox",
    mode: "balanced",
    capabilities: ["voice-clone", "inline-tags"],
    languages: ["en"],
    approval: "evaluation",
    releaseStage: "internal",
    localEligible: false,
  },
  {
    id: "tada-1b@evaluation",
    label: "TADA 1B",
    family: "tada",
    mode: "balanced",
    capabilities: ["voice-clone", "long-form"],
    languages: ["en"],
    approval: "evaluation",
    releaseStage: "internal",
    localEligible: false,
  },
  {
    id: "tada-3b-ml@evaluation",
    label: "TADA 3B Multilingual",
    family: "tada",
    mode: "studio",
    capabilities: ["voice-clone", "long-form", "multilingual"],
    languages: [],
    approval: "evaluation",
    releaseStage: "internal",
    localEligible: false,
  },
  {
    id: "fish-s2-pro@commercial-gate",
    label: "Fish S2-Pro",
    family: "fish-speech",
    mode: "studio",
    capabilities: ["voice-clone", "multi-speaker", "inline-tags", "streaming"],
    languages: [],
    approval: "license-blocked",
    releaseStage: "internal",
    localEligible: false,
  },
  {
    id: "moss-soundeffect-v2@evaluation",
    label: "MOSS-SoundEffect-v2",
    family: "moss-tts",
    mode: "studio",
    capabilities: ["sfx-generation"],
    languages: ["en", "zh"],
    approval: "evaluation",
    releaseStage: "internal",
    localEligible: false,
  },
  {
    id: "whisper@evaluation",
    label: "Whisper",
    family: "whisper",
    mode: "balanced",
    capabilities: ["transcription", "alignment-input"],
    languages: [],
    approval: "evaluation",
    releaseStage: "internal",
    localEligible: true,
  },
  {
    id: "qwen3-0.6b@evaluation",
    label: "Qwen3 0.6B Helper",
    family: "qwen3",
    mode: "fast",
    capabilities: ["metadata", "manuscript-assistance", "schema-output"],
    languages: [],
    approval: "evaluation",
    releaseStage: "internal",
    localEligible: true,
  },
] as const;

export const modelsRoutes: FastifyPluginAsync = async (app) => {
  app.get(
    "/",
    {
      schema: {
        tags: ["Models"],
        summary: "List approved and evaluating model routes",
        response: {
          200: Type.Object({
            registryRevision: Type.String(),
            routes: Type.Array(ModelRouteSchema),
          }),
        },
      },
    },
    async () => ({ registryRevision: "registry_2026-08-03.1", routes: modelRoutes }),
  );
};
